repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        types: [python]
        args: ["--py38-plus"]
      - id: reorder-python-imports
        name: Reorder python imports
        entry: reorder-python-imports
        language: python
        types: [python]
        args: ["--application-directories", "src"]
      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [python]
      - id: ruff
        name: ruff
        entry: ruff
        language: python
        require_serial: true
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix]
      - id: pre-commit-hooks
        name: fix UTF-8 byte order marker
        entry: fix-byte-order-marker
        language: python
        types: [text]
      - id: pre-commit-hooks
        name: Trim trailing whitespace
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
      - id: pre-commit-hooks
        name: Fix End of Files
        entry: end-of-file-fixer
        language: python
        types: [text]
